# Generated by Django 3.2.9 on 2021-11-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='age_category',
            field=models.IntegerField(choices=[(1929, '19~29'), (3049, '30~49'), (5064, '50~64')], max_length=50),
        ),
    ]
