# Generated by Django 3.2.9 on 2021-11-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_standard_age_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='codename',
            new_name='n_code',
        ),
    ]
