# Generated by Django 3.2.9 on 2021-11-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
