# Generated by Django 3.2.9 on 2021-11-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211115_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='proper_cal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
