# Generated by Django 3.2.9 on 2021-11-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_proper_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.FloatField(choices=[(1.2, '거의 없음'), (1.375, '활동량 조금있다.(주1~2회 운동)'), (1.55, '활동량 많다.(주3~5회 운동)'), (1.725, '활동량 꽤 많다.(주6~7회 운동)'), (1.9, '활동량 아주 많다.(매일 2번 운동)')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age_category',
            field=models.IntegerField(choices=[(1929, '19~29'), (3049, '30~49'), (5064, '50~64')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(),
        ),
    ]
