# Generated by Django 3.2.9 on 2021-11-16 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='%Y/%m/<django.db.models.fields.related.ForeignKey>/')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('mealtimes', models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], max_length=20)),
                ('n_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_code', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='upload_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_info',
            },
        ),
    ]
