# Generated by Django 3.2.9 on 2021-11-16 13:00

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_code', models.CharField(blank=True, db_column='n_code', max_length=20, null=True, verbose_name=accounts.models.User)),
                ('image', models.ImageField(max_length=200, upload_to=upload.utils.upload_to_func)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mealtimes', models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_upload_info',
            },
        ),
    ]
