# Generated by Django 3.2.9 on 2021-11-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upload',
            table='user_upload_info',
        ),
    ]
