# Generated by Django 3.2.9 on 2021-11-16 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='n_code',
            field=models.ForeignKey(blank=True, db_column='n_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
