# Generated by Django 3.2.9 on 2021-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='n_code',
            field=models.CharField(blank=True, db_column='n_code', max_length=20, null=True),
        ),
    ]
