# Generated by Django 3.2.9 on 2021-11-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_upload_n_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='n_code',
        ),
    ]
